### ISSUE TITLE
OF version?

### ISSUE THREAD

**Issue by bradfichter** [kylemcdonald/ofxFaceTracker#92]
Does this only work with a specific version of OF?  I'm using 0.8.4 on Win 7 using VS. I update the project to point to /vs/openframeworksLib (from /vs2010/) and imported the project. Tried in 2012 an 2010. Getting a lot of errors that all look similar to these:

`Error	1	error C2061: syntax error : identifier '_Dynamic_tag'	C:\_Tools\OpenFrameworks\of_v0.8.4_vs_release\libs\openFrameworks\types\ofTypes.h	188	1	openframeworksLib`

`Error	2	error C2535: 'ofPtr<T>::ofPtr(const ofPtr<Tp1> &)' : member function already defined or declared	C:\_Tools\OpenFrameworks\of_v0.8.4_vs_release\libs\openFrameworks\types\ofTypes.h	188	1	openframeworksLib`

I am rather new to OF so it could be something obvious to you.

Thanks!

**Comment by kylemcdonald** [comment]
this should work on 0.8.4 and github branch `master` for openFrameworks. the errors you're getting look like openFrameworks issues, try using the examples and if those don't work please report a bug on the main openFrameworks repo.
