### PR TITLE
fix returning value

### PR DESCRIPTION
**Pull request by edap**
With the new OF version (0.10), I'm having this error on linux
/Sources/of_v0.10.0_linux64gcc6_release/addons/ofxFaceTracker/src/ofxFaceTracker.cpp:46: error: control reaches end of non-void function [-Werror=return-type]
 }

This commit fix this error.

### CODE REVIEW

**Comment by edap** [comment]
Anything I can do to get this merged? The addon is not working on linux with 0.10 otherwise.

**Comment by genekogan** [comment]
this is confirmed working for me on mac, so i will merge this.
